name: Newman Run


on:
  schedule:
    - cron: '0 1-23 * * *'
    - cron: '0 0 * * *'
  


jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: matt-ball/newman-action@postman
        with:
          apiKey: ${{ secrets.postmanApiKey }}
          collection: Book_collection.postman_collection.json
          environment: 5922408-228c7edd-fc15-4f68-9665-a35d7df6945b
